name: Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: tripletexjs
          default-branch: next

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
          cache: yarn

      - run: yarn install

      - run: yarn run build

      - run: yarn test
        env:
          CI: true

      - uses: codecov/codecov-action@v2

      - if: ${{ steps.release.outputs.release_created }}
        run: yarn publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: yarn build-storybook

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.BJERKBOT_GITHUB_TOKEN }}
          publish_dir: ./storybook-static